### ISSUE TITLE
Can't flash firmware to ax3600 - firmware is too large

### ISSUE THREAD

**Issue by kolaa** [jingleijack/Openwrt_Beta#15]
root@OpenWrt:~# ubiformat /dev/mtd12 -y -f /tmp/openwrt-ipq807x-generic-xiaomi_ax3600-squashfs-nand-factory.ubi
ubiformat: mtd12 (nand), size 37486592 bytes (35.8 MiB), 286 eraseblocks of 131072 bytes (128.0 KiB), min. I/O size 2048 bytes
libscan: scanning eraseblock 285 -- 100 % complete
ubiformat: 286 eraseblocks have valid erase counter, mean value is 0
ubiformat: error!: file "/tmp/openwrt-ipq807x-generic-xiaomi_ax3600-squashfs-nand-factory.ubi" is too large (46399488 bytes)
           error 0 (No error information)

**Comment by jingleijack** [comment]
双系统？双系统建议安装AP版本，或者精简版本

**Comment by kolaa** [comment]
是的，双系统。 固件成功了，但是密码是多少？，空不行

**Comment by GianmariaZanchetta** [comment]
Hi everyone, do you Remember how to fix this issue? I am stuck in the same situation
