### ISSUE TITLE
5.15内核的nss问题求教

### ISSUE THREAD

**Issue by AXBNG** [jingleijack/Openwrt_Beta#30]
我在Boos大的github下提及nss的问题，得到如下回复，大佬看下什么意思
![360截图20220415164334588](https://user-images.githubusercontent.com/89022914/163548592-71f70daf-77e9-4062-8bbc-8e2eb0ec1c75.jpg)

**Comment by jingleijack** [comment]
> 我在Boos大佬的github下提及nss的问题，得到如下回复，大佬看下什么意思 ![360截图20220415164334588](https://user-images.githubusercontent.com/89022914/163548592-71f70daf-77e9-4062-8bbc-8e2eb0ec1c75.jpg)

检查pined(root还是非root)编译的过程？
